version: "2.1"

networks:
  mo_net:
    name: mo_net
    external: true

volumes:
  fb-office:

services:
  firebird:
    container_name: firebird
    restart: always
    image: jacobalberty/firebird:2.5.9-sc
    networks:
      - mo_net
    ports:
      - 3050:3050
      - 3070:3070
    volumes:
      - fb-office:/firebird
    environment:
      - TZ=Europe/Moscow
      - RemoteAuxPort=3070
      - ISC_PASSWORD=masterkey
    env_file:
      - stack.env
