version: '2.1'

networks:
  mo_net:
    name: mo_net
    external: true
 
services:
  firebird:
    container_name: firebird
    restart: always
    image: jacobalberty/firebird:2.5.9-sc
    networks:
      - mo_net
    ports:
      - 3050:3050
      - 3070:3070
    volumes:
      - /mirokon/docker/volume/firebird:/firebird
      - backup:/backup 
    environment:
      - TZ=Europe/Moscow
      - ISC_PASSWORD=masterkey

volumes:
  backup:
    driver: local
    driver_opts:
        type: nfs
        o: nfsvers=4,addr=10.100.10.253,rw
        device: ":/export/backup-fb"
    
  
